# rubocop configuration file
#
# rubocop is a static code analyzer, also called a linter, for Ruby.
#
# more info on rubocop: https://docs.rubocop.org/rubocop/index.html
# more info on this file: https://docs.rubocop.org/rubocop/configuration.html

require:
  - rubocop-rspec # https://docs.rubocop.org/rubocop-rspec/index.html
  - rubocop-rails # https://docs.rubocop.org/rubocop-rails/index.html

AllCops:
  Exclude:
    - 'bin/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - '.github/**/*'
    - db/schema.rb

Bundler/OrderedGems:
  Enabled: false

##Metrics Cops https://docs.rubocop.org/rubocop/1.36/cops_metrics.html
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Max: 50
Metrics/LineLength:
  Enabled: false
Metrics/BlockLength:
  Max: 30

# Lint Cops https://docs.rubocop.org/rubocop/1.36/cops_lint.html
Lint/NonLocalExitFromIterator:
  Enabled: false

#Style Cops https://docs.rubocop.org/rubocop/1.36/cops_style.html
Style/Documentation:
  Enabled: false
Style/FloatDivision:
  Enabled: false
Style/GlobalVars:
  Enabled: true
  AllowedVariables:
    - $redis
#Style/ClassAndModuleChildren:
#  Enabled: true
Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 16
Metrics/PerceivedComplexity:
  Enabled: true
  Max: 16
Metrics/ModuleLength:
  Enabled: true
  Max: 300

# Naming https://docs.rubocop.org/rubocop/cops_naming.html
Naming/VariableName:
  EnforcedStyle: snake_case
Naming/VariableNumber:
  EnforcedStyle: snake_case

#RSpec Cops https://docs.rubocop.org/rubocop-rspec/index.html
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/AnyInstance:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Max: 20
RSpec/MessageSpies:
  Enabled: false
RSpec/NestedGroups:
  Max: 6
RSpec/RepeatedExampleGroupBody:
  Enabled: false
RSpec/FilePath:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false

# Rails Cops https://docs.rubocop.org/rubocop-rails/index.html
Rails/FilePath:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false
